Add missing FaceDetectionApi.h
from http://dl.linux-sunxi.org/SDK/A23-v1.0/unpacked/A23/

target thumb C++: camera.polaris <= device/explay/fog/hardware/camera/HALCameraFactory.cpp
In file included from device/explay/fog/hardware/camera/HALCameraFactory.h:9:0,
                 from device/explay/fog/hardware/camera/HALCameraFactory.cpp:12:
device/explay/fog/hardware/camera/CameraHardware2.h:18:30: fatal error: FaceDetectionApi.h: No such file or directory