camera: add missing include
target thumb C++: camera.polaris <= device/explay/fog/hardware/camera/PreviewWindow.cpp
In file included from hardware/libhardware/include/hardware/camera.h:20:0,
                 from device/explay/fog/hardware/camera/V4L2CameraDevice.h:12,
                 from device/explay/fog/hardware/camera/PreviewWindow.cpp:12:
hardware/libhardware/include/hardware/camera_common.h:27:39: fatal error: system/camera_vendor_tags.h: No such file or directory