Add missing videodev2.h
from http://dl.linux-sunxi.org/SDK/A23-v1.0/unpacked/A23/

target thumb C++: camera.polaris <= device/explay/fog/hardware/camera/PreviewWindow.cpp
In file included from device/explay/fog/hardware/camera/PreviewWindow.cpp:12:0:
device/explay/fog/hardware/camera/V4L2CameraDevice.h:13:23: fatal error: videodev2.h: No such file or directory

target thumb C++: camera.polaris <= device/explay/fog/hardware/camera/PreviewWindow.cpp
In file included from device/explay/fog/hardware/camera/CameraHardware2.h:16:0,
                 from device/explay/fog/hardware/camera/HALCameraFactory.h:9,
                 from device/explay/fog/hardware/camera/HALCameraFactory.cpp:12:
device/explay/fog/hardware/include/videodev2.h:57:27: fatal error: videodev2_new.h: No such file or directory